<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVFeyacg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVFeyacg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVFeyacg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVFeyacg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVFeyacg\App_KernelDevDebugContainer([
    'container.build_hash' => 'VFeyacg',
    'container.build_id' => 'cae7b73e',
    'container.build_time' => 1750252975,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVFeyacg');
